/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gymer.GUI;

import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import gymer.DAO.*;
import gymer.entities.*;
import gymer.utilities.*;
import gymer.utilities.*;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

public class QL_baocao extends javax.swing.JInternalFrame {

    
    private Employee em = new Employee();
    private RPDetails rp = new RPDetails();
    private ReportImp rpi = new ReportImp();
    private BillTraining bt = new BillTraining();
    private BillTrainingImp bti =  new BillTrainingImp();
    private Customer cs = new Customer();
    private CustomerImp csi =  new CustomerImp();
    private boolean TAP;
    private boolean HANG;
    private boolean DICHVU;
    private boolean SANPHAM;
    private GoodsImp svi = new GoodsImp();
    private Goods sv = new Goods();
    private List<RPDetails> data = new ArrayList<RPDetails>();
    private List<RPDetails> graphdata = new ArrayList<RPDetails>();
    private BillGoodsImp bgi = new BillGoodsImp();
    /**
     * Creates new form QL_baocao
     */
    public QL_baocao() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi=(BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        deState();
        CttDontap.setVisible(false);
        CttHang.setVisible(false);
        stateHandler(null);
    }
    
    public void setEm (Employee in){
        this.em = in;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pmain = new javax.swing.JPanel();
        TB_tkTap = new javax.swing.JScrollPane();
        Tb_hang2 = new javax.swing.JTable();
        TB_tkHang = new javax.swing.JScrollPane();
        Tb_hang1 = new javax.swing.JTable();
        TB_hang = new javax.swing.JScrollPane();
        Tb_hang = new javax.swing.JTable();
        Tb_tap = new javax.swing.JScrollPane();
        TB_tap = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jR_TKsanpham = new javax.swing.JRadioButton();
        jR_TKdichvu = new javax.swing.JRadioButton();
        jR_HDhang = new javax.swing.JRadioButton();
        jR_HDtap = new javax.swing.JRadioButton();
        jTextField16 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        CttHang = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        tenNV1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CttDontap = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        tenNV = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1230, 650));
        setPreferredSize(new java.awt.Dimension(1230, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pmain.setBackground(new java.awt.Color(255, 255, 255));
        Pmain.setForeground(new java.awt.Color(255, 255, 255));
        Pmain.setPreferredSize(new java.awt.Dimension(1230, 630));
        Pmain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tb_hang2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Tb_hang2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên gói tập", "Đã bán ", "Doanh thu"
            }
        ));
        Tb_hang2.setRowHeight(25);
        Tb_hang2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tb_hang2MouseClicked(evt);
            }
        });
        TB_tkTap.setViewportView(Tb_hang2);

        Pmain.add(TB_tkTap, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 316, 1080, 260));

        Tb_hang1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Tb_hang1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên sản phẩm", "Sô lượng bán được", "Tồn kho", "Doanh thu"
            }
        ));
        Tb_hang1.setRowHeight(25);
        Tb_hang1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tb_hang1MouseClicked(evt);
            }
        });
        TB_tkHang.setViewportView(Tb_hang1);

        Pmain.add(TB_tkHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 316, 1080, 260));

        Tb_hang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Tb_hang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Ngày tạo", "Tên khách", "Số điện thoại khách", "Tên người tạo", "Mã nhân viên", "Tổng tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tb_hang.setRowHeight(25);
        Tb_hang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tb_hangMouseClicked(evt);
            }
        });
        TB_hang.setViewportView(Tb_hang);

        Pmain.add(TB_hang, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 316, 1080, 260));

        TB_tap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TB_tap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Ngày tạo", "Dịch vụ", "Tên khách hàng", "SĐT", "Tên người tạo", "Mã nhân viên", "Tổng tiền"
            }
        ));
        TB_tap.setRowHeight(25);
        TB_tap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TB_tapMouseClicked(evt);
            }
        });
        Tb_tap.setViewportView(TB_tap);

        Pmain.add(Tb_tap, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 316, 1080, 260));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gymer/Image/Xuất file.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setDefaultCapable(false);
        jButton2.setFocusPainted(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Pmain.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 590, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Báo cáo & Thống kê");
        Pmain.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 41, 450, 53));

        jButton5.setBackground(new java.awt.Color(51, 153, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Biểu đồ");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        Pmain.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 590, -1, 35));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jR_TKsanpham.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jR_TKsanpham.setText("Thống kê doanh thu sản phẩm");
        jR_TKsanpham.setBorder(null);
        jR_TKsanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jR_TKsanphamMouseClicked(evt);
            }
        });
        jR_TKsanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR_TKsanphamActionPerformed(evt);
            }
        });
        jPanel1.add(jR_TKsanpham, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, -1, 40));

        jR_TKdichvu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jR_TKdichvu.setText("Thống kê doanh thu dịch vụ");
        jR_TKdichvu.setBorder(null);
        jR_TKdichvu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jR_TKdichvuMouseClicked(evt);
            }
        });
        jPanel1.add(jR_TKdichvu, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, 40));

        jR_HDhang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jR_HDhang.setText("Báo cáo hóa đơn hàng");
        jR_HDhang.setBorder(null);
        jR_HDhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jR_HDhangMouseClicked(evt);
            }
        });
        jPanel1.add(jR_HDhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 210, 40));

        jR_HDtap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jR_HDtap.setText("Báo cáo hóa đơn tập");
        jR_HDtap.setBorder(null);
        jR_HDtap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jR_HDtapMouseClicked(evt);
            }
        });
        jPanel1.add(jR_HDtap, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 210, 40));

        jTextField16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField16.setToolTipText("Tìm kiếm");
        jTextField16.setBorder(null);
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        jTextField16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField16KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 490, 20));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gymer/Image/Check_shadow.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setDefaultCapable(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 120, -1, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gymer/Image/find.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 560, 60));
        jPanel1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 230, 25));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Từ ngày");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Đến ngày");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, -1, 24));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 230, 25));

        Pmain.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1230, 190));

        getContentPane().add(Pmain, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 1230, 650));

        CttHang.setPreferredSize(new java.awt.Dimension(1230, 650));
        CttHang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(102, 102, 102));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel38.setText("Nhân viên lập:");

        tenNV1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tenNV1.setForeground(new java.awt.Color(102, 102, 102));
        tenNV1.setText("jLabel1");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Chi tiết hóa đơn bán hàng");

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gymer/Image/Back.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setDefaultCapable(false);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Tên");

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(102, 102, 102));
        jLabel39.setText("Mã hóa đơn:");

        jTextField9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tên sản phẩm", "Số lượng", "Tổng tiển"
            }
        ));
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);

        jLabel7.setText("Tổng thành tiền");

        jTextField14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel44.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(102, 102, 102));
        jLabel44.setText("Tên khách hàng:");

        jLabel45.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(102, 102, 102));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel45.setText("SĐT:");
        jLabel45.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jTextField15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gymer/Image/Xóa.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1070, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(410, 410, 410)
                                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tenNV1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)))))
                .addGap(84, 84, 84))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel25)
                .addGap(31, 31, 31)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tenNV1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)))
        );

        CttHang.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 650));

        getContentPane().add(CttHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 1230, 650));

        CttDontap.setMinimumSize(new java.awt.Dimension(1230, 630));
        CttDontap.setPreferredSize(new java.awt.Dimension(1230, 630));
        CttDontap.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gymer/Image/Back.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 559, 90, -1));

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(102, 102, 102));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField6.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField6.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 370, 360, 30));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(102, 102, 102));
        jLabel34.setText("Mã hóa đơn:");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, 90, 30));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(102, 102, 102));
        jLabel35.setText("Dịch vụ");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 50, -1));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(102, 102, 102));
        jLabel36.setText("Ngày bắt đầu");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, -1, -1));

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(102, 102, 102));
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField8.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField8.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 330, 360, -1));

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(51, 51, 51));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField1.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 370, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("Tên");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 52, -1));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(102, 102, 102));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel37.setText("Giá");
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 80, -1));

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 370, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("Địa chỉ");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 102));
        jLabel27.setText("SĐT");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(51, 51, 51));
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 370, -1));

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 370, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText("CMND");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setText("Giới tính");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(51, 51, 51));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7d(evt);
            }
        });
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 370, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(102, 102, 102));
        jLabel30.setText("Năm sinh");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gymer/Image/Xóa.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1062, 559, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 118, 10, 330));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Chi tiết hóa đơn tập");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 331, 41));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(102, 102, 102));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel33.setText("Nhân viên lập:");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 500, 100, -1));

        tenNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tenNV.setForeground(new java.awt.Color(102, 102, 102));
        tenNV.setText("jLabel1");
        jPanel2.add(tenNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 500, 150, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(102, 102, 102));
        jLabel32.setText("Khách hàng");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 450, -1));

        jTextField17.setEditable(false);
        jTextField17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField17.setForeground(new java.awt.Color(102, 102, 102));
        jTextField17.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField17.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField17.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField17.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, 360, -1));

        jTextField18.setEditable(false);
        jTextField18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField18.setForeground(new java.awt.Color(102, 102, 102));
        jTextField18.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField18.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField18.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField18.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 290, 360, -1));

        jTextField19.setEditable(false);
        jTextField19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField19.setForeground(new java.awt.Color(102, 102, 102));
        jTextField19.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField19.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField19.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField19.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 370, -1));

        jTextField20.setEditable(false);
        jTextField20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField20.setForeground(new java.awt.Color(102, 102, 102));
        jTextField20.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField20.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField20.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField20.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 180, 360, -1));

        jLabel46.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(102, 102, 102));
        jLabel46.setText("Ngày tạo");
        jPanel2.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 90, 30));

        CttDontap.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 650));

        getContentPane().add(CttDontap, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 1230, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deState () {
        this.DICHVU = false;
        this.TAP = false;
        this.HANG = false;
        this.SANPHAM = false;
    }
    
    
    
    private void stateHandler (List input) {
        this.data = input;
        QL_baocao.this.setVisible(true);
        Pmain.setVisible(true);
        CttDontap.setVisible(false);
        CttHang.setVisible(false);
        QL_baocao.this.revalidate();
        if (this.DICHVU == true) {
            showDataDV(input);
            jR_TKsanpham.setSelected(false);
            jR_HDhang.setSelected(false);
            jR_HDtap.setSelected(false);
            Tb_tap.setVisible(false);
            TB_hang.setVisible(false);
            TB_tkHang.setVisible(false);
            TB_tkTap.setVisible(true);
            QL_baocao.this.revalidate();
            this.SANPHAM = false;
            this.TAP = false;
            this.HANG = false;
        }
        if (this.HANG == true) {
            showDataHang(input);
            jR_TKsanpham.setSelected(false);
            jR_TKdichvu.setSelected(false);
            jR_HDtap.setSelected(false);
            Tb_tap.setVisible(false);
            TB_hang.setVisible(true);
            TB_tkHang.setVisible(false);
            TB_tkTap.setVisible(false);
            QL_baocao.this.revalidate();
            this.SANPHAM = false;
            this.DICHVU = false;
            this.TAP = false;
        }
        if (this.TAP == true) {
            showDataTap(input);
            jR_TKsanpham.setSelected(false);
            jR_HDhang.setSelected(false);
            jR_TKdichvu.setSelected(false);
            Tb_tap.setVisible(true);
            TB_hang.setVisible(false);
            TB_tkHang.setVisible(false);
            TB_tkTap.setVisible(false);
            QL_baocao.this.revalidate();
            this.SANPHAM = false;
            this.DICHVU = false;
            this.HANG = false;
        }
        if (this.SANPHAM == true) {
            showDataHangHoa(input);
            jR_TKdichvu.setSelected(false);
            jR_HDhang.setSelected(false);
            jR_HDtap.setSelected(false);
            Tb_tap.setVisible(false);
            TB_hang.setVisible(false);
            TB_tkHang.setVisible(true);
            TB_tkTap.setVisible(false);
            QL_baocao.this.revalidate();
            this.HANG = false;
            this.DICHVU = false;
            this.TAP = false;
        }
        if (this.DICHVU == false && this.HANG == false && this.SANPHAM == false && this.TAP == false) {
            jR_TKdichvu.setSelected(false);
            jR_HDhang.setSelected(false);
            jR_HDtap.setSelected(false);
            jR_TKsanpham.setSelected(false);
            Tb_tap.setVisible(false);
            TB_hang.setVisible(false);
            TB_tkHang.setVisible(false);
            TB_tkTap.setVisible(false);
            QL_baocao.this.revalidate();
        }
    }
    
    
    // hien thi trong phan chi tiet
    private void setHangDetails () {
        int index = Tb_hang.getSelectedRow();
        TableModel model = Tb_hang.getModel();
        CttHang.setVisible(true);
        Pmain.setVisible(false);
        int selectedRow = Tb_hang.getSelectedRow();
        jTextField9.setText(model.getValueAt(selectedRow, 0).toString());
        jTextField14.setText(model.getValueAt(selectedRow, 2).toString());
        jTextField15.setText(model.getValueAt(selectedRow, 3).toString());
        tenNV1.setText(model.getValueAt(selectedRow, 4).toString());
        jTextField10.setText(model.getValueAt(selectedRow, 6).toString());      
        List<BillGoods_Details> input = new ArrayList<BillGoods_Details>();
        input = bgi.getDetails(jTextField9.getText());
        DefaultTableModel model1 = (DefaultTableModel)jTable1.getModel();
        model1.setRowCount(0);
        Object row[] = new Object[3];
        for (int i=0 ; i<input.size() ; i++){
            sv = svi.findByID(input.get(i).getMaHang());
            row[0] = sv.getTen();
            row[1] = input.get(i).getSoLuong();
            row[2] = sv.getGia() * input.get(i).getSoLuong();
            model1.addRow(row);
        }
    }
    
    // hien thi trong phan chi tiet
    private void setTapDetails () {
        int index = TB_tap.getSelectedRow();
        TableModel model = TB_tap.getModel();
        CttDontap.setVisible(true);
        Pmain.setVisible(false);
        int selectedRow = TB_tap.getSelectedRow();
        jTextField17.setText(model.getValueAt(selectedRow, 0).toString());
        jTextField20.setText(model.getValueAt(selectedRow, 1).toString());
        jTextField18.setText(model.getValueAt(selectedRow, 2).toString());
        jTextField1.setText(model.getValueAt(selectedRow, 3).toString());
        jTextField4.setText(model.getValueAt(selectedRow, 4).toString());
        tenNV.setText(model.getValueAt(selectedRow, 5).toString());
        jTextField6.setText(model.getValueAt(selectedRow, 6).toString());
        this.bt = bti.findByMaHD(jTextField17.getText());
        jTextField8.setText(DateTime.convertReadable(this.bt.getNgay()));
        this.cs = this.csi.findByID_1(bt.getMaKH());
        jTextField3.setText(this.cs.getAddress());
        jTextField5.setText(this.cs.getCMND());
        if (this.cs.getSex()){
            jTextField7.setText("Nữ");
        }
        jTextField7.setText("Nam");
        jTextField19.setText(Integer.toString(this.cs.getYearofBirh()));
    }
    
    
    private void showDataTap(List<RPDetails> input){
        DefaultTableModel model = (DefaultTableModel)TB_tap.getModel();
        model.setRowCount(0);
        Object row[] = new Object[8];
        for (int i=0 ; i<input.size() ; i++){
            row[0] = input.get(i).getMaHD();
            row[1] = input.get(i).getNgayLap();
            row[2] = input.get(i).getTenDV();
            row[3] = input.get(i).getTenKhach();
            row[4] = input.get(i).getSDTKhach();
            row[5] = input.get(i).getTenNV();
            row[6] = input.get(i).getMaNV();
            row[7] = input.get(i).getTongTien();
            model.addRow(row);
        }
    }
    
    private void showDataHang(List<RPDetails> input){
        DefaultTableModel model = (DefaultTableModel)Tb_hang.getModel();
        model.setRowCount(0);
        Object row[] = new Object[7];
        for (int i=0 ; i<input.size() ; i++){
            row[0] = input.get(i).getMaHD();
            row[1] = input.get(i).getNgayLap();
            row[2] = input.get(i).getTenKhach();
            row[3] = input.get(i).getSDTKhach();
            row[4] = input.get(i).getTenNV();
            row[5] = input.get(i).getMaNV();
            row[6] = input.get(i).getTongTien();
            model.addRow(row);
        }
    }
    
    
    private void showDataDV(List<RPDetails> input){
        DefaultTableModel model = (DefaultTableModel)Tb_hang2.getModel();
        model.setRowCount(0);
        Object row[] = new Object[3];
        for (int i=0 ; i<input.size() ; i++){
            row[0] = input.get(i).getTenDV();
            row[1] = input.get(i).getSoLuongDichVu();
            row[2] = input.get(i).getTongTien();
            model.addRow(row);
        }
    }
    
    private void showDataHangHoa(List<RPDetails> input){
        DefaultTableModel model = (DefaultTableModel)Tb_hang1.getModel();
        model.setRowCount(0);
        Object row[] = new Object[4];
        for (int i=0 ; i<input.size() ; i++){
            row[0] = input.get(i).getTenDV();
            row[1] = input.get(i).getSoLuongDichVu();
            row[2] = input.get(i).getTonKho();
            row[3] = input.get(i).getTongTien();
            model.addRow(row);
        }
    }
    
    
    private void jR_TKsanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jR_TKsanphamMouseClicked
        // TODO add your handling code here:
        deState();
        this.SANPHAM = true;
        stateHandler(rpi.getAllHangHoa());
    }//GEN-LAST:event_jR_TKsanphamMouseClicked

    private void jR_HDhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jR_HDhangMouseClicked
        // TODO add your handling code here:     
        deState();
        this.HANG = true;
        stateHandler(rpi.getAllHang());
    }//GEN-LAST:event_jR_HDhangMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Chọn nơi lưu báo cáo");
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int userSelection = fileChooser.showSaveDialog(null);
        String path;
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            path = fileChooser.getSelectedFile().getAbsolutePath();
            if (this.TAP == true) {
                ExcelFiles.createRPBillTraining(this.data, path);
            }
            if (this.HANG == true) {
                ExcelFiles.createRPBillGoods(this.data, path);
            }
            if (this.DICHVU == true) {
                ExcelFiles.createRPServices(this.data, path);
            }
            if (this.SANPHAM == true) {
                ExcelFiles.createRPGoods(this.data, path);
            }
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        stateHandler(rpi.getAllTap());
    }//GEN-LAST:event_jButton3MouseClicked

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        // TODO add your handling code here:
//        this.cs = csi.findBySDT_1(jTextField4.getText());
//        if (!this.cs.getID().equals("")){
//            setCustoText(this.cs);
//            checker1 = true;
//            //System.out.println("scsd");
//        }
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jTextField7d(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7d
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7d

    private void Tb_hangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tb_hangMouseClicked
        // TODO add your handling code here:
        setHangDetails();
    }//GEN-LAST:event_Tb_hangMouseClicked

    private void TB_tapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TB_tapMouseClicked
        // TODO add your handling code here:
        setTapDetails();
    }//GEN-LAST:event_TB_tapMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        stateHandler(rpi.getAllHang());
    }//GEN-LAST:event_jButton4MouseClicked

    private void jR_HDtapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jR_HDtapMouseClicked
        // TODO add your handling code here:
        deState();
        this.TAP = true;
        stateHandler(rpi.getAllTap());
    }//GEN-LAST:event_jR_HDtapMouseClicked

    private void jR_TKdichvuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jR_TKdichvuMouseClicked
        // TODO add your handling code here:
        deState();
        this.DICHVU = true;
        stateHandler(rpi.getAllDichVuTap());
    }//GEN-LAST:event_jR_TKdichvuMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        int dialogButton = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa ?");
        if (dialogButton == JOptionPane.YES_OPTION) {
            if (this.bti.delete(jTextField17.getText())){
                JOptionPane.showMessageDialog(null, "Xóa thành công");
                String Reason = JOptionPane.showInputDialog("Lý do xóa");
                LogFile.createDeleteLog(em.getMaNV(), em.getTen(), jTextField17.getText(), Reason, LogFile.HOADONTAP);
                stateHandler(rpi.getAllHang());
            }
            else JOptionPane.showMessageDialog(null, "Có lỗi trong quá trình xóa vui lòng thử lại");
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        BillGoodsImp bgi = new BillGoodsImp();
        int dialogButton = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa ?");
        if (dialogButton == JOptionPane.YES_OPTION) {
            if (bgi.delete(jTextField9.getText())){
                JOptionPane.showMessageDialog(null, "Xóa thành công");
                String Reason = JOptionPane.showInputDialog("Lý do xóa");
                LogFile.createDeleteLog(em.getMaNV(), em.getTen(), jTextField9.getText(), Reason, LogFile.HOADONHANG);
                stateHandler(rpi.getAllTap());
            }
            else JOptionPane.showMessageDialog(null, "Có lỗi trong quá trình xóa vui lòng thử lại");
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String date1, date2;
        Date d1 = jDateChooser2.getDate();
        Date d2 = jDateChooser1.getDate();
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        date1 = df.format(d1);
        date2 = df.format(d2);
        if (this.TAP == true) {           
            stateHandler(rpi.getDataTap(date1, date2));
        }
        if (this.HANG == true) {
            stateHandler(rpi.getDataHang(date1, date2));
        }
        if (this.DICHVU == true) {
            stateHandler(rpi.getDichVuTapbyDate(date1, date2));
        }
        if (this.SANPHAM == true) {
            stateHandler(rpi.getAllHangHoabyDate(date1, date2));
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void Tb_hang1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tb_hang1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Tb_hang1MouseClicked

    private void Tb_hang2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tb_hang2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Tb_hang2MouseClicked

    private void jTextField16KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField16KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (this.TAP == true) {
                stateHandler(rpi.getAllTapbyString(jTextField16.getText()));
            }
            if (this.HANG == true){
                stateHandler(rpi.getAllHangbyString(jTextField16.getText()));
            }
        }
    }//GEN-LAST:event_jTextField16KeyPressed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        Graph grp;
        if (this.DICHVU) {
            grp = new Graph(this.data,1);
        }
        if (this.SANPHAM) {
            grp = new Graph(this.data,1);
        }
        if (this.TAP) {
            grp = new Graph(rpi.getTapforGraphAll(),1);
        }
        if (this.HANG) {
            grp = new Graph(rpi.getHangforGraphAll(),1);
        }
        
    }//GEN-LAST:event_jButton5MouseClicked

    private void jR_TKsanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR_TKsanphamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jR_TKsanphamActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CttDontap;
    private javax.swing.JPanel CttHang;
    private javax.swing.JPanel Pmain;
    private javax.swing.JScrollPane TB_hang;
    private javax.swing.JTable TB_tap;
    private javax.swing.JScrollPane TB_tkHang;
    private javax.swing.JScrollPane TB_tkTap;
    private javax.swing.JTable Tb_hang;
    private javax.swing.JTable Tb_hang1;
    private javax.swing.JTable Tb_hang2;
    private javax.swing.JScrollPane Tb_tap;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jR_HDhang;
    private javax.swing.JRadioButton jR_HDtap;
    private javax.swing.JRadioButton jR_TKdichvu;
    private javax.swing.JRadioButton jR_TKsanpham;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel tenNV;
    private javax.swing.JLabel tenNV1;
    // End of variables declaration//GEN-END:variables
}